/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockVerifier } from "./MockVerifier";
export type { TruthAttestation } from "./TruthAttestation";
