/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockVerifierInterface extends Interface {
  getFunction(
    nameOrSignature: "isVerified" | "verified" | "verify"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MockVerified"): EventFragment;

  encodeFunctionData(
    functionFragment: "isVerified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "verified", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "verify", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace MockVerifiedEvent {
  export type InputTuple = [payloadHash: BytesLike];
  export type OutputTuple = [payloadHash: string];
  export interface OutputObject {
    payloadHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): MockVerifier;
  waitForDeployment(): Promise<this>;

  interface: MockVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isVerified: TypedContractMethod<[payloadHash: BytesLike], [boolean], "view">;

  verified: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verify: TypedContractMethod<[payloadHash: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[payloadHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verified"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<[payloadHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "MockVerified"
  ): TypedContractEvent<
    MockVerifiedEvent.InputTuple,
    MockVerifiedEvent.OutputTuple,
    MockVerifiedEvent.OutputObject
  >;

  filters: {
    "MockVerified(bytes32)": TypedContractEvent<
      MockVerifiedEvent.InputTuple,
      MockVerifiedEvent.OutputTuple,
      MockVerifiedEvent.OutputObject
    >;
    MockVerified: TypedContractEvent<
      MockVerifiedEvent.InputTuple,
      MockVerifiedEvent.OutputTuple,
      MockVerifiedEvent.OutputObject
    >;
  };
}
